# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
	v.memory = 4096
  end

  config.vm.network "forwarded_port", guest: 6060, host: 6060
  config.vm.synced_folder ".", "/vagrant", type:"virtualbox"

  config.vm.provision "shell", inline: <<-SHELL
    chmod +x ../scripts/install.sh
    bash -c '../scripts/install.sh'
  SHELL
end